### ISSUE TITLE
Can we create a choropleth map with a slider?

### ISSUE THREAD

**Issue by BurgerBurglar** [datawrapper/snippets#6]
[Ideally like this](https://ourworldindata.org/explorers/countries-in-conflict-data?time=2015&facet=none&Measure=Conflict+deaths&Conflict+type=All+armed+conflicts&Conflict+sub-type=Across+all+sub-types&country=AFG~ETH~SYR~UKR)

![image](https://github.com/datawrapper/snippets/assets/33530007/0ca734f5-a5ed-4094-8295-f7ca8a116bc6)

**Comment by ejb** [comment]
Hi @BurgerBurglar! (Great handle btw.) I recommend contacting support@datawrapper.de with any questions you might have about using Datawrapper. They will be more than happy to help.

**Comment by BurgerBurglar** [comment]
thank you.
